export const POPULATE_CATEGORIES = 'POPULATE_CATEGORIES';
export const POPULATE_POSTS = 'POPULATE_POSTS';
export const UPDATE_POST = 'UPDATE_POST';
export const REMOVE_POST = 'REMOVE_POST';
export const POPULATE_COMMENTS = 'POPULATE_COMMENTS';
export const UPDATE_COMMENT = 'UPDATE_COMMENT';
export const REMOVE_COMMENT = 'REMOVE_COMMENT';

export const SET_POST_SORT_METHOD = 'SET_POST_SORT_METHOD';
export const SET_COMMENT_SORT_METHOD = 'SET_COMMENT_SORT_METHOD';